/**
 * SeededBrands — Brand opportunities for the affiliate marketplace.
 */

export const SEEDED_BRANDS = [
  { id:'razer', name:'Razer', category:'tech', emoji:'🐍', tagline:'For Gamers By Gamers',
    commissionRate:12, avgOrderValue:150, minFollowers:1000, minStreams:5,
    budget:50000, spent:12400, color:'#00ff00',
    products:[
      {id:'r1',name:'BlackWidow V4 Keyboard',price:169.99,commission:20.4,img:'⌨️'},
      {id:'r2',name:'DeathAdder V3 Mouse',price:89.99,commission:10.8,img:'🖱️'},
      {id:'r3',name:'Kraken V3 Headset',price:129.99,commission:15.6,img:'🎧'},
      {id:'r4',name:'Raptor 27" Monitor',price:349.99,commission:42.0,img:'🖥️'},
    ],
    requirements:['Gaming content','1k+ followers','Active streams'],
    tags:['gaming','peripherals','esports'],
  },
  { id:'logitech', name:'Logitech G', category:'tech', emoji:'🎯', tagline:'Play Legendary',
    commissionRate:10, avgOrderValue:120, minFollowers:500, minStreams:3,
    budget:75000, spent:28000, color:'#0078d7',
    products:[
      {id:'l1',name:'G Pro X Superlight Mouse',price:159.99,commission:16.0,img:'🖱️'},
      {id:'l2',name:'G915 TKL Keyboard',price:249.99,commission:25.0,img:'⌨️'},
      {id:'l3',name:'G Pro X Gaming Headset',price:129.99,commission:13.0,img:'🎧'},
    ],
    requirements:['Tech content','500+ followers'],
    tags:['gaming','peripherals'],
  },
  { id:'nike', name:'Nike', category:'fashion', emoji:'✔️', tagline:'Just Do It',
    commissionRate:8, avgOrderValue:110, minFollowers:2000, minStreams:0,
    budget:300000, spent:89000, color:'#f05a28',
    products:[
      {id:'nk1',name:'Air Max 2025',price:180.0,commission:14.4,img:'👟'},
      {id:'nk2',name:'Jordan 1 Retro High OG',price:170.0,commission:13.6,img:'👟'},
      {id:'nk3',name:'Tech Fleece Hoodie',price:130.0,commission:10.4,img:'👕'},
    ],
    requirements:['2k+ followers','Lifestyle/fitness content'],
    tags:['fashion','sports','lifestyle'],
  },
  { id:'adidas', name:'Adidas', category:'fashion', emoji:'⚡', tagline:'Impossible Is Nothing',
    commissionRate:9, avgOrderValue:95, minFollowers:1000, minStreams:0,
    budget:250000, spent:71000, color:'#000000',
    products:[
      {id:'ad1',name:'Ultraboost 24',price:190.0,commission:17.1,img:'👟'},
      {id:'ad2',name:'Samba OG',price:100.0,commission:9.0,img:'👟'},
    ],
    requirements:['1k+ followers'],
    tags:['fashion','sports'],
  },
  { id:'fenty', name:'Fenty Beauty', category:'beauty', emoji:'💄', tagline:'Beauty For All',
    commissionRate:14, avgOrderValue:65, minFollowers:500, minStreams:0,
    budget:90000, spent:34000, color:'#ff557e',
    products:[
      {id:'fb1',name:'Pro Filt\'r Foundation',price:38.0,commission:5.32,img:'💄'},
      {id:'fb2',name:'Gloss Bomb',price:22.0,commission:3.08,img:'💋'},
      {id:'fb3',name:'Killawatt Highlighter',price:38.0,commission:5.32,img:'✨'},
    ],
    requirements:['500+ followers','Beauty content'],
    tags:['beauty','makeup','inclusive'],
  },
  { id:'morphe', name:'Morphe', category:'beauty', emoji:'🎨', tagline:'The Artist\'s Playground',
    commissionRate:18, avgOrderValue:55, minFollowers:500, minStreams:0,
    budget:60000, spent:18000, color:'#e64a8c',
    products:[
      {id:'mp1',name:'35B Color Glam Palette',price:35.0,commission:6.3,img:'🎨'},
      {id:'mp2',name:'Fluffy Brush Set',price:42.0,commission:7.56,img:'🖌️'},
    ],
    requirements:['500+ followers'],
    tags:['beauty','makeup','affordable'],
  },
  { id:'gfuel', name:'G FUEL', category:'food', emoji:'⚡', tagline:'The Official Drink of Esports',
    commissionRate:20, avgOrderValue:35, minFollowers:500, minStreams:2,
    budget:80000, spent:42000, color:'#e40000',
    products:[
      {id:'gf1',name:'G FUEL Tub (40 srv)',price:35.99,commission:7.2,img:'🥤'},
      {id:'gf2',name:'G FUEL Can (12 pack)',price:29.99,commission:6.0,img:'🥫'},
    ],
    requirements:['500+ followers','Gaming/streaming content'],
    tags:['food','gaming','energy'],
  },
  { id:'myprotein', name:'MyProtein', category:'fitness', emoji:'💪', tagline:'Fueling Your Goals',
    commissionRate:16, avgOrderValue:55, minFollowers:500, minStreams:0,
    budget:70000, spent:32000, color:'#ffa500',
    products:[
      {id:'mp3',name:'Impact Whey Protein 5kg',price:54.99,commission:8.8,img:'🥛'},
      {id:'mp4',name:'Creatine Monohydrate',price:19.99,commission:3.2,img:'💊'},
    ],
    requirements:['500+ followers','Fitness/health content'],
    tags:['fitness','supplements','health'],
  },
  { id:'gymshark', name:'Gymshark', category:'fashion', emoji:'🦈', tagline:'Be a Visionary',
    commissionRate:13, avgOrderValue:80, minFollowers:1000, minStreams:0,
    budget:120000, spent:38000, color:'#25252d',
    products:[
      {id:'gs1',name:'Vital Seamless Leggings',price:65.0,commission:8.45,img:'🩳'},
      {id:'gs2',name:'Crest Hoodie',price:60.0,commission:7.8,img:'👕'},
    ],
    requirements:['1k+ followers','Fitness/lifestyle content'],
    tags:['fashion','fitness','activewear'],
  },
  { id:'elgato', name:'Elgato', category:'tech', emoji:'📹', tagline:'Build a Better Studio',
    commissionRate:11, avgOrderValue:180, minFollowers:500, minStreams:3,
    budget:60000, spent:22000, color:'#1e1e2e',
    products:[
      {id:'eg8',name:'Stream Deck MK.2',price:149.99,commission:16.5,img:'🎚️'},
      {id:'eg9',name:'HD60 X Capture Card',price:149.99,commission:16.5,img:'📹'},
      {id:'eg10',name:'Key Light',price:199.99,commission:22.0,img:'💡'},
      {id:'eg11',name:'Wave:3 Microphone',price:149.99,commission:16.5,img:'🎙️'},
    ],
    requirements:['500+ followers','Streaming/content creation'],
    tags:['streaming','tech','content'],
  },
  { id:'steelseries', name:'SteelSeries', category:'tech', emoji:'🎮', tagline:'Play For Free',
    commissionRate:11, avgOrderValue:140, minFollowers:1000, minStreams:5,
    budget:45000, spent:18000, color:'#e8202f',
    products:[
      {id:'ss1',name:'Arctis Nova Pro',price:249.99,commission:27.5,img:'🎧'},
      {id:'ss2',name:'Apex Pro TKL',price:219.99,commission:24.2,img:'⌨️'},
    ],
    requirements:['1k+ followers','Gaming content'],
    tags:['gaming','peripherals'],
  },
  { id:'supreme', name:'Supreme', category:'fashion', emoji:'🔴', tagline:'Supreme New York',
    commissionRate:15, avgOrderValue:250, minFollowers:5000, minStreams:0,
    budget:80000, spent:22000, color:'#d40000',
    products:[
      {id:'sp1',name:'Box Logo Hoodie',price:348.0,commission:52.2,img:'👕'},
      {id:'sp2',name:'Box Logo Tee',price:158.0,commission:23.7,img:'👕'},
    ],
    requirements:['5k+ followers','Streetwear content'],
    tags:['fashion','streetwear','hype'],
  },
  { id:'charlotte_tilbury', name:'Charlotte Tilbury', category:'beauty', emoji:'🌹', tagline:'Magic In A Bottle',
    commissionRate:12, avgOrderValue:90, minFollowers:1000, minStreams:0,
    budget:100000, spent:28000, color:'#c8a96e',
    products:[
      {id:'ct1',name:'Magic Cream',price:115.0,commission:13.8,img:'✨'},
      {id:'ct2',name:'Flawless Filter',price:49.0,commission:5.88,img:'💄'},
    ],
    requirements:['1k+ followers','Beauty/luxury content'],
    tags:['beauty','luxury','skincare'],
  },
  { id:'coinbase', name:'Coinbase', category:'fintech', emoji:'₿', tagline:'The Easiest Place to Buy Crypto',
    commissionRate:0, flatRate:10, avgOrderValue:0, minFollowers:1000, minStreams:0,
    budget:200000, spent:55000, color:'#0052ff',
    products:[
      {id:'cb1',name:'Sign Up + First Trade',price:0,commission:10,img:'💰'},
    ],
    requirements:['1k+ followers','Finance/tech content'],
    tags:['crypto','fintech'],
    specialNote:'$10 per verified new user',
  },
  { id:'liquid_death', name:'Liquid Death', category:'food', emoji:'💀', tagline:'Murder Your Thirst',
    commissionRate:16, avgOrderValue:30, minFollowers:1000, minStreams:0,
    budget:40000, spent:12000, color:'#1a1a1a',
    products:[
      {id:'ld1',name:'Mountain Water Case',price:23.99,commission:3.84,img:'💧'},
    ],
    requirements:['1k+ followers','Alternative/edgy content'],
    tags:['food','water','alt'],
  },
  { id:'ring', name:'Ring', category:'home', emoji:'🔔', tagline:'Neighbors Helping Neighbors',
    commissionRate:7, avgOrderValue:200, minFollowers:2000, minStreams:0,
    budget:80000, spent:24000, color:'#1c7ed6',
    products:[
      {id:'rg1',name:'Video Doorbell 4',price:199.99,commission:14.0,img:'🔔'},
      {id:'rg2',name:'Stick Up Cam',price:99.99,commission:7.0,img:'📹'},
    ],
    requirements:['2k+ followers','Home/tech content'],
    tags:['home','security','tech'],
  },
  { id:'blue_yeti', name:'Blue Microphones', category:'tech', emoji:'🎙️', tagline:'Legendary Sound',
    commissionRate:10, avgOrderValue:130, minFollowers:500, minStreams:2,
    budget:40000, spent:15000, color:'#0070c0',
    products:[
      {id:'by1',name:'Yeti USB Microphone',price:129.99,commission:13.0,img:'🎙️'},
      {id:'by2',name:'Yeti X Pro',price:169.99,commission:17.0,img:'🎙️'},
    ],
    requirements:['500+ followers','Streaming/podcast content'],
    tags:['audio','streaming','podcast'],
  },
  { id:'bang', name:'Bang Energy', category:'food', emoji:'💥', tagline:'Potent Brain & Body Fuel',
    commissionRate:18, avgOrderValue:40, minFollowers:500, minStreams:0,
    budget:60000, spent:28000, color:'#ffd700',
    products:[
      {id:'bg1',name:'Bang Energy 12 Pack',price:24.99,commission:4.5,img:'🥫'},
    ],
    requirements:['500+ followers'],
    tags:['food','energy','fitness'],
  },
  { id:'hyperx', name:'HyperX', category:'tech', emoji:'👑', tagline:'We\'re All Gamers',
    commissionRate:12, avgOrderValue:110, minFollowers:500, minStreams:3,
    budget:40000, spent:14000, color:'#d01012',
    products:[
      {id:'hx1',name:'Cloud Alpha Headset',price:99.99,commission:12.0,img:'🎧'},
      {id:'hx2',name:'Alloy Origins Core',price:109.99,commission:13.2,img:'⌨️'},
    ],
    requirements:['500+ followers','Gaming content'],
    tags:['gaming','peripherals'],
  },
  { id:'samsung', name:'Samsung', category:'tech', emoji:'📱', tagline:'Do What You Can\'t',
    commissionRate:5, avgOrderValue:800, minFollowers:5000, minStreams:10,
    budget:200000, spent:45000, color:'#1428a0',
    products:[
      {id:'s1',name:'Galaxy S25 Ultra',price:1299.99,commission:65.0,img:'📱'},
      {id:'s2',name:'Odyssey Neo G9 Monitor',price:1999.99,commission:100.0,img:'🖥️'},
    ],
    requirements:['5k+ followers','Tech/lifestyle content'],
    tags:['tech','mobile','displays'],
  },
];

export const BRAND_CATEGORIES = [
  { id:'all',     label:'All Brands',  icon:'🏪', color:'#a855f7' },
  { id:'tech',    label:'Tech',        icon:'💻', color:'#06b6d4' },
  { id:'fashion', label:'Fashion',     icon:'👗', color:'#ec4899' },
  { id:'beauty',  label:'Beauty',      icon:'💄', color:'#f472b6' },
  { id:'food',    label:'Food',        icon:'🍕', color:'#f59e0b' },
  { id:'fitness', label:'Fitness',     icon:'💪', color:'#10b981' },
  { id:'home',    label:'Home',        icon:'🏠', color:'#8b5cf6' },
  { id:'fintech', label:'Fintech',     icon:'💰', color:'#fbbf24' },
];

export const getBrandsByCategory = (cat) => cat==='all' ? SEEDED_BRANDS : SEEDED_BRANDS.filter(b=>b.category===cat);
export const getFeaturedBrands = (limit=6) => SEEDED_BRANDS.filter(b=>b.budget>80000).slice(0,limit);
export const getTopPayingBrands = (limit=10) => [...SEEDED_BRANDS].sort((a,b)=>b.commissionRate-a.commissionRate).slice(0,limit);
